# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Jian
tagline:          'A Programming Blog'
description:      'A Programming Blog'
url:              https://jianloong.github.io/
baseurl:          
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

permalink:        pretty

author:         
  name:           'Jian Loong Liew'
  url:            https://twitter.com/JianLoongLiew

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

disqus:
  shortname: jianloonggithubio

plugins_dir:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

url: "https://jianliew.me"

plugins:
  [jekyll-paginate, jekyll-sitemap, jekyll-feed]
 
# Custom vars
version:            3.4.1
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/JianLoong/
